### ISSUE TITLE
I don't know how to contact you

### ISSUE THREAD

**Issue by epmvito** [qqizhao/Awesome-rPPG-Method-List#1]
I wrote to you by email, but did not receive a response, I decided that you missed my email and I decided to write to you here.

**Comment by qqizhao** [comment]
I checked my mailbox but didn't find your letter.  What's wrong with this?

**Comment by seven0813** [comment]
> I wrote to you by email, but did not receive a response, I decided that you missed my email and I decided to write to you here.

I checked my mailbox but didn't find your letter. What's wrong with this?

**Comment by epmvito** [comment]
I emailed you again, check your emailbox again (zhaoqqi@foxmail.com), if there is no email there again you can leave another channel for communication.
